<script setup lang="ts">
import WelcomeItem from "./WelcomeItem.vue";
import DocumentationIcon from "./icons/IconDocumentation.vue";
</script>

<template>
  <WelcomeItem>
    <template #icon>
      <DocumentationIcon />
    </template>
    <template #heading>Usage</template>
    Follow the link generated by the
    <a
      target="_blank"
      href="http://github.com/totev/vodafone-station-cli"
    >vodafone-station-cli tool</a> when ran with the
    <i>docsis -w</i> option
    . It contains the docsis values in JSON.
  </WelcomeItem>
</template>
